server:
  port: 8080
# 配置项目信息
spring:
  application:
    name: tlais-web-management
  # 配置数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  # 文件上传相关配置
  servlet:
    multipart:
      # 最大单个文件大小
      max-file-size: 10MB
      # 最大请求总大小
      max-request-size: 10MB
# 配置mybatis-plus
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启  驼峰命名
    map-underscore-to-camel-case: true

# 配置事务管理的日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

# aliyun相关,在类中通过@value 获取
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucket-name: java-ai-yince
    region: cn-beijing

# jwt相关
com:
  jwt:
    user-secret-key: VmpGa2MyUldhM2xXVjJSU1lsUnJlRmxyWkZkTmJHeFpVMjF6UFE9PQ== # 秘钥
    user-ttl: 7200000 # 用户token过期时间
    user-token-name: authentication # 用户token名称